#***************USE YOUR OWN TIDB ************
spring.application.name=MySpringWeb
server.port=8080


#Database Configuration
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://gateway01.us-west-2.prod.aws.tidbcloud.com:4000/JavaDB
spring.datasource.username=SMumwStnVSYG4og.root
spring.datasource.password=IuspiUMnmvmg35cO

#JPA Configuration - Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=np03cs4a240047@heraldcollege.edu.np
spring.mail.password=resy aprl ruue hkoj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
jwt.secret=c8f7d4a1e96b3f8d2c5a7e1b9d4f3a8c6e2f7d1a9b5c3e8f4d7a2c6b1e9f3a5d
jwt.expiration=86400000
