#***************USE YOUR OWN TIDB ************
#***************USE YOUR OWN TIDB ************
#***************USE YOUR OWN TIDB ************
#***************USE YOUR OWN TIDB ************
#***************USE YOUR OWN TIDB ************
spring.application.name=MySpringWeb
server.port=8080


#Database Configuration
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/test
spring.datasource.username=sMxa6m3VwBQ3MKJ.root
spring.datasource.password=FbHB925PRf9YLFN9

#JPA Configuration - Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


